- name: Ansible playbook to create all the roboshop project jobs in jenkins server.
  hosts: localhost
  roles:
     - jenkins-jobs
  vars:
     folders:
        - APP-SETUP-WITH-ANSIBLE
        - Infrastructure

     pipeline_jobs:
        - { jobName: "roboshop", folderName: "APP-SETUP-WITH-ANSIBLE", repoName: "roboshop-ansible", fileNme: "Jenkinsfile" }
        - { jobName: "cart", folderName: "Infrastructure", repoName: "cart-infra", fileNme: "Jenkinsfile" }
        - { jobName: "catalogue", folderName: "Infrastructure", repoName: "catalogue-infra", fileNme: "Jenkinsfile" }
        - { jobName: "user", folderName: "Infrastructure", repoName: "user-infra", fileNme: "Jenkinsfile" }
        - { jobName: "frontend", folderName: "Infrastructure", repoName: "frontend-infra", fileNme: "Jenkinsfile" }
        - { jobName: "shipping", folderName: "Infrastructure", repoName: "shipping-infra", fileNme: "Jenkinsfile" }
        - { jobName: "payment", folderName: "Infrastructure", repoName: "payment-infra", fileNme: "Jenkinsfile" }
        - { jobName: "DESTROY", folderName: "Infrastructure", repoName: "roboshop-jenkins", fileNme: "Jenkinsfile-Destroy-Infra" }
