- name: Ansible playbook to create all the roboshop project jobs in jenkins server.
  hosts: localhost
  roles:
     - jenkins-jobs
  vars:
     folders:
        - APP-SETUP-WITH-ANSIBLE
     pipeline_jobs:
        - { jobName: "roboshop", folderName: "APP-SETUP-WITH-ANSIBLE", repoName: "roboshop-ansible" }
